# Generated by Django 4.2.7 on 2023-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('person', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
